### ISSUE TITLE
Is there any plan to upgrade the Here SDK to latest version?

### ISSUE THREAD

**Issue by hanatharesh2712** [aquawill/here_android_premium_sdk_test#3]
This app is built on Here SDK 3.* and currently, the latest version is 4.7.*. so, I want to know that if there is any plan to upgrade the APP to the latest Here SDK version.
Thanks!

**Comment by aquawill** [comment]
Hi, SDK 3.x and 4.x is not compatible, so it's not possible to directly upgrade this repo from 3.x to 4.x.
